DEVICE_TEXT = "GRUTTO"
DEFAULT_BAUD  = 19200

WINDOW_HORIZONTAL_RES = 1024
WINDOW_VERTICAL_RES = 600

NUM_LASER_SENSORS = 4

#HOW OFTEN A REDUNDANT WRITE OF THE SENSOR DATA IS DONE
#SET TO 0 FOR NO REDUNDANT WRITES
REDUNDANT_WRITE_METER = 0.1 

ARDUINO_DEV_STRING = "usb-Arduino__www.arduino.cc"
GPS_DEV_STRING = "u-blox_AG_-_www.u-blox.com_u-blox_GNSS_receiver"

DATA_DIRECTORY = "/home/dmz/GruttoData"
